# Generated by Django 3.0.4 on 2023-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201119_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENFERMEIRO', 'Enfermeiro'), ('TÉCNICO', 'Técnico'), ('MÉDICO', 'Médico')], default='TÉCNICO', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *'),
        ),
    ]
