# Generated by Django 3.0.4 on 2023-04-06 11:44

import django.contrib.auth.models
from django.db import migrations
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20230406_0830'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('enfermeiros', usuario.models.EnfermeiroAtivoManager()),
                ('tecnicos', usuario.models.TecnicoAtivoManager()),
                ('medicos', usuario.models.MedicoAtivoManager()),
            ],
        ),
    ]
